services:
  db:
    image: postgres:16
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - APP_ID=${APP_ID}
      - APP_SECRET=${APP_SECRET}
      - SIGNING_KEY=${SIGNING_KEY}
      - APPSTORE_URL=${APPSTORE_URL}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    volumes:
      - .:/app
      - ../wam/dist:/app/wam/dist
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
